language: python

python:
  - "3.5"

install:
  - pip install -r requirements.txt

before_script:
  - python setup.py build_ext --inplace

script:
  - nosetests
  - coverage run tests.py

after_success:
  - codecov
