language: python
sudo: required
cache: packages
notifications:
  email:
    on_success: never
    on_failure: always
install:
  - pip install bs4
  - pip install requests
  - pip install lxml
  - pip install tqdm
script:
  - pytest
