language: python

python:
  - "3.5"

install:
  - pip install -r requirements.txt

before_script:
  - python setup.py build_ext --inplace

script:
  - nosetests
  - coverage run lingcorpora/pl_corpus.py
  - coverage run lingcorpora/ger_corpus.py


after_success:
  - codecov --token=daf0f956-0ddc-4546-bba4-d287455ad247
